# Base image
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the remaining application code
COPY . .

# Build the React app
# RUN yarn build

# Expose the desired port (e.g., 3000 for React development server)
EXPOSE 3000

# Define the command to run the React app
CMD ["yarn", "start"]
