# Use uma imagem base do Node.js
# FROM node:alpine

# # Defina o diretório de trabalho dentro do contêiner
# WORKDIR /app

# # Copie o arquivo package.json e o arquivo package-lock.json (se existir)
# COPY package*.json ./

# # Execute o comando npm install para instalar as dependências
# RUN npm install

# # Copie todo o código-fonte para o diretório de trabalho
# COPY . .

# # Exponha a porta 3000 para acesso externo
# EXPOSE 3000

# # Inicie o aplicativo ReactJS
# CMD ["npm", "start"]

# Base image
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the remaining application code
COPY . .

# Build the React app
# RUN yarn build

# Expose the desired port (e.g., 3000 for React development server)
EXPOSE 3000

# Define the command to run the React app
CMD ["yarn", "start"]
